module.exports = {
    alps: require('./alps'),
    button: require('./button'),
    choc: require('./choc'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
    mx: require('./mx'),
    oled: require('./oled'),
    omron: require('./omron'),
    pad: require('./pad'),
    promicro: require('./promicro'),
    rgb: require('./rgb'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    trrs: require('./trrs'),
    via: require('./via'),
    reversible_battery: require("./reversible_battery"),
    button2: require("./button2"),
    niceview: require("./niceview"),
    nicenano: require("./nicenano"),
    mountinghole: require("./mountinghole"),
    diode2: require("./diode2"),
    led_strip: require("./led_strip"),
    tenting_puck: require("./tenting_puck"),
}
